---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-access
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-access-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-gke-access
    namespace: default
roleRef:
  kind: ClusterRole
  name: prometheus-access
  apiGroup: rbac.authorization.k8s.io
