global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: pod
    bearer_token_file: /etc/prometheus/prometheus-token  # reference the token file
    tls_config:
      ca_file: /etc/prometheus/secrets/ca.crt  # use the GKE CA cert if needed
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: "monitoring|default"
