#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: 'kubernetes'
#    kubernetes_sd_configs:
#      - role: pod
#        api_server: http://35.202.160.183/
#    bearer_token_file: /home/ec2-user/prometheus-token
#    tls_config:
#      insecure_skip_verify: true
#    relabel_configs:
#      - source_labels: [__meta_kubernetes_namespace]
#        action: keep
#        regex: "monitoring|default"
#    scrape_configs:
#      - job_name: 'node_exporter'
#        scrape_interval: 5s
#        static_configs:
#          - targets: [ 'http://13.51.70.225:9100' ]

---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['http://13.51.70.225:9090']

  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: pod
        api_server: http://35.202.160.183/
    bearer_token_file: /home/ec2-user/prometheus-token
    tls_config:
      ca_file: /etc/prometheus/secrets/ca.crt
      #insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: "monitoring|default"
