#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: 'kubernetes'
#    kubernetes_sd_configs:
#      - role: pod
#        api_server: http://35.202.160.183/
#    bearer_token_file: /home/ec2-user/prometheus-token
#    tls_config:
#      insecure_skip_verify: true
#    relabel_configs:
#      - source_labels: [__meta_kubernetes_namespace]
#        action: keep
#        regex: "monitoring|default"
#    scrape_configs:
#      - job_name: 'node_exporter'
#        scrape_interval: 5s
#        static_configs:
#          - targets: [ 'http://13.51.70.225:9100' ]

---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: pod
        api_server: https://34.122.62.35
    bearer_token_file: /etc/prometheus/secrets/prometheus-token
    tls_config:
      ca_file: /etc/prometheus/secrets/ca.crt
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: "monitoring|default"

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.128.0.3:9200', '10.128.0.4:9200', '10.128.0.5:9200']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['35.202.160.183:8080']


