global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'kubernetes'
    kubernetes_sd_configs:
      - role: pod
        api_server: https://34.122.62.35:443
    bearer_token_file: /etc/prometheus/secrets/prometheus-token
    tls_config:
      ca_file: /etc/prometheus/secrets/ca.crt
      insecure_skip_verify: false
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: "monitoring|default"

  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - kube-system
    tls_config:
      ca_file: /etc/prometheus/secrets/ca.crt
      insecure_skip_verify: false
    relabel_configs:
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: metrics