apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-app
  template:
    metadata:
      labels:
        app: abc-app
    spec:
      containers:
        - name: abc-app
          image: emmas4impact/abc-technologies:latest
          ports:
            - containerPort: 8080
