---
- hosts: jenkins
  become: yes
  tasks:
    - name: Pull Docker image
      docker_image:
        name: emmas4impact/abc-technologies
        tag: latest
        source: pull

    - name: Start Docker container
      docker_container:
        name: abc-app
        image: emmas4impact/abc-technologies:latest
        state: started
        ports:
          - "8080:8080"
