---
- name: Deploy Application to GKE
  hosts: local
  tasks:
    - name: Apply Deployment to GKE
      command: kubectl apply -f ./kubernetes/deployment.yml
    - name: Apply Service to GKE
      command: kubectl apply -f ./kubernetes/service.yml

