---
- name: Deploy Application to GKE
  hosts: local
  tasks:
    - name: Apply Deployment to GKE
      command: kubectl apply -f /devops_capstone/kubernetes/deployment.yaml
    - name: Apply Service to GKE
      command: kubectl apply -f /devops_capstone/kubernetes/service.yaml

