- name: Deploy Application to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        src:  ../k8s-configs/abc-deployment.yaml

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        src: "{{ playbook_dir }}/../k8s-configs/abc-service.yaml"
